apiVersion: v1
kind: List
items:
  -
    apiVersion: v1
    kind: BuildConfig
    metadata:
      name: curl
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'curl:latest'
      runPolicy: Serial
      source:
        git:
          uri: 'https://github.com/cpitman/demo-curl-callback.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'centos:latest'
        type: Docker
      triggers:
        -
          type: ConfigChange
        -
          imageChange:
          type: ImageChange
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      name: centos
    spec:
      tags:
        -
          from:
            kind: DockerImage
            name: 'centos:latest'
          importPolicy:
          name: latest
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      name: curl
    spec:
      tags:
        -
          name: latest
